### ISSUE TITLE
plot response curves per species

### ISSUE THREAD

**Issue by billspat** [SpaCE-Lab-MSU/bg_sdm_refactor#1]
from @bgerstner90  : 

>Can we add a few lines of code after the ENMevaluate function that then writes the response curves for each species to a file? 
>To create a plot for each species X radius X run, code is 

```R
# e.mx.1 <- ENMevaluate output
pdf("species_response_curve.pdf")
dismo::response(e.mx.1@models[[1]])
dev.off()
```

but this does not aggregate curves across species radii.  Since when we run on radius, we only the one radius output available, we have to 

 1. save all the model outputs (for all radii) in the species folder  at run time
    - need to name files for species and radius to keep them straight (like we already do for other outputs)
    - can save this model output as an Rdata file if it's more complex than what a CSV can do
 3. after the model runs are all done  have a (new) script read in the outputs from all the radii
    - can read into a list structure keyed by radius   if `radius <- 1` then `e.mx[[radius]] == e.mx.1` 
 5. aggregate some how?
 6. plot aggregation for the species

@bgerstner90 : how to aggregate multiple model outputs for plotting?  Or do you just one one page with many plots on them in a matrix?

**Comment by billspat** [comment]
note that to keep making progress on this I'm going to save the outputs as Rdata and also make plots that are for each species X radius  which is not ideal but I can start running the jobs and if the data is saved, can figure out how to aggregate later.

**Comment by bgerstner90** [comment]
@billspat  I think having one pdf with all of the radii run plots being its own page in the pdf. So we'll have one pdf per species summarizing all the radii runs. Maybe that's the easiest way to do it?
